### ISSUE TITLE
表删除了

### ISSUE THREAD

**Issue by yuzhubo-yu** [Jzjzzzz/vblog#2]
item_bank表删除了不能文件上传了，求给表或者表属性

**Comment by Jzjzzzz** [comment]
我更新数据库文件了，项目后续还会更新对你有帮助的话帮忙点个start。

**Comment by Jzjzzzz** [comment]
> item_bank表删除了不能文件上传了，求给表或者表属性



> item_bank表删除了不能文件上传了，求给表或者表属性


我更新数据库文件了，项目后续还会更新对你有帮助的话帮忙点个start。

**Comment by Jzjzzzz** [comment]
> item_bank表删除了不能文件上传了，求给表或者表属性

我更新数据库文件了，项目后续还会更新对你有帮助的话帮忙点个start。
